server:
  port: 8080

mysql:
  host: localhost
  port: 3307
  user: root
  password: Zzy20061017
  dbname: flash_sale

redis:
  addr: localhost:6380
  password:  ""
  db: 0

rabbitmq:
  url : amqp://guest:guest@localhost:5672/