services:

  redis:
    image: redis:7
    container_name: flash-sale-redis
    restart: always
    ports:
      - "6380:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  mysql:
    image: mysql:8.0
    container_name: flash-sale-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Zzy20061017
      MYSQL_DATABASE: flash_sale
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
